spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.tufkgheysihozerkorzq}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:v9qZBnaAtqidtIFs}

# Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Ver si dejamos esto
server.port=${PORT:8080} 
jwt.secret.key=${JWT_SECRET_KEY:unaClaveSuperLargaDePruebaParaLocal1234567890}